// POST /api/contracts-create   (admin only — requires Supabase session Bearer token)
// Body (JSON):
//   title?, template?            — defaults: meta.title, 'intermediere'
//   meta:   { nr, data, eyebrow, subtitle }
//   terms:  { propertyText, pret, comision, comisionPrag, durata }
//   signers: [ { role, name, email } ]   // order = display position; all links go out at once
//
// Creates the contract + signer rows, emails each signer their personal link.
// → 201 { ok, contract_id, signers: [{ role, name, email, token, url }] }

const supabase = require('./_supabase');
const { buildSections } = require('./_contracts/content');
const { sendEmail, inviteEmail } = require('./_contracts/notify');

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function baseUrl(req) {
  if (process.env.PUBLIC_BASE_URL) return process.env.PUBLIC_BASE_URL.replace(/\/$/, '');
  const proto = (req.headers['x-forwarded-proto'] || 'https').split(',')[0];
  const host = req.headers['x-forwarded-host'] || req.headers.host;
  return `${proto}://${host}`;
}

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // --- admin auth: verify the Supabase session JWT ---
  const auth = req.headers.authorization || '';
  const jwt = auth.startsWith('Bearer ') ? auth.slice(7) : null;
  if (!jwt) return res.status(401).json({ error: 'Neautentificat' });
  const { data: userData, error: authErr } = await supabase.auth.getUser(jwt);
  if (authErr || !userData || !userData.user) return res.status(401).json({ error: 'Sesiune invalidă' });

  const { title, template, meta = {}, terms = {}, signers } = req.body || {};

  if (!Array.isArray(signers) || signers.length === 0)
    return res.status(400).json({ error: 'Cel puțin un semnatar este obligatoriu' });
  for (const s of signers) {
    if (!s || !s.email || !EMAIL_RE.test(s.email))
      return res.status(400).json({ error: 'Fiecare semnatar trebuie să aibă un email valid' });
  }

  const contractTitle = title || meta.title || 'Contract de intermediere imobiliară';

  // 1) contract row
  const { data: contract, error: cErr } = await supabase
    .from('contracts')
    .insert({
      status: 'sent',
      template: template || 'intermediere',
      title: contractTitle,
      data: { meta, terms, sections: buildSections(terms) },
      sent_at: new Date().toISOString(),
    })
    .select('id')
    .single();
  if (cErr) {
    console.error('contract insert error:', cErr);
    return res.status(500).json({ error: 'Eroare la crearea contractului' });
  }

  // 2) signer rows (tokens auto-generated by the DB default)
  const rows = signers.map((s, i) => ({
    contract_id: contract.id,
    position: i + 1,
    role: s.role || null,
    name: s.name || null,
    email: s.email,
    status: 'pending',
  }));
  const { data: signerRows, error: sErr } = await supabase
    .from('contract_signers')
    .insert(rows)
    .select('role, name, email, token');
  if (sErr) {
    console.error('signers insert error:', sErr);
    // roll back the contract so we don't leave an orphan
    await supabase.from('contracts').delete().eq('id', contract.id);
    return res.status(500).json({ error: 'Eroare la crearea semnatarilor' });
  }

  // 3) email each signer their personal link
  const base = baseUrl(req);
  const out = signerRows.map((r) => ({ ...r, url: `${base}/sign.html?token=${r.token}` }));
  await Promise.all(out.map((r) =>
    sendEmail({
      to: r.email,
      subject: `[EVEN] Semnează: ${contractTitle}`,
      html: inviteEmail({ signerName: r.name, role: r.role, contractTitle, url: r.url, total: out.length }),
    })
  ));

  return res.status(201).json({ ok: true, contract_id: contract.id, signers: out });
};
